### PR TITLE
Add docs for unit test.

### PR DESCRIPTION
**Pull request by windyGex**
Please review it, especially English version.
@developit

### CODE REVIEW

**Comment by windyGex** [comment]
My English is not well, so I'm afraid to write error English grammar and Please review whether the content needs to be modified for people that reading docs.

**Comment by windyGex** [comment]
Any news?

**Comment by developit** [comment]
Hi @windyGex - sorry for the delay on this.  I've reviewed the English version and made some changes, most notably I changed the URL and title of both versions.  If you're able, it would be good to sync that up with the chinese version. Cheers!

**Comment by windyGex** [comment]
Thx. I have translate to Chinese by your version.

**Pull request merged**
