### PR TITLE
Adds The New York Times to We are Using page

### PR DESCRIPTION
**Pull request by caiogondim**

### CODE REVIEW

**Comment by jt3k** [comment]
How did you determine that this page uses preact?
I looked at the source code and did not find anything other than React jQuery requirejs and other

**Comment by caiogondim** [comment]
Hello, I work for The New York Times on the Video team.
Our media player uses Preact, and it is embed on news page.

Let me know if you want to change the URL better reflect the project we use Preact for.

**Comment by developit** [comment]
It's exciting that others can see NYT using Preact now 😍

**Comment by Tushkiz** [comment]
Hey @caiogondim,
I am curious to know about the media player usage, is it blogged somewhere?

Thanks

**Comment by caiogondim** [comment]
Not yet.
We are working on decoupling the player from New York Times business logic to open source it. But no deadlines for now.

**Comment by Tushkiz** [comment]
Great, I will keep scanning your twitter feed for an update 😬

**Pull request merged**
