### PR TITLE
Get started on API Reference documentation

### PR DESCRIPTION
**Pull request by wildlyinaccurate**
Following the discussion on #131, I've started on an _API Reference_ page. I'm opening the PR now to promote early feedback ⭐️ 

I realise that this page will probably duplicate some of the content on other pages, but I'm not sure that's necessarily a bad thing. Hopefully I'm not the only person who heads straight for the API Reference page whenever I need to remember how to do something!

My todo list for this page so far is:

- [x] Document the return types for each `Component` lifecycle method.
- [x] An example of a stateless functional component.
- [x] Some examples for `render()` including how to replace server-rendered content.

### CODE REVIEW

**Comment by developit** [comment]
Looks awesome so far!  Should we wait to merge, or get this out in its current state?

**Comment by wildlyinaccurate** [comment]
I've had a busy couple of weeks. I'd intended to write a bit more before we merge it. I also wanted to ask you what position in the navigation this should take. Maybe I should move it to the bottom?

**Comment by developit** [comment]
I was actually thinking it could entirely replace the "Lifecycle Methods" link, especially if we copied that table into this page.

**Comment by wildlyinaccurate** [comment]
Forgot to ping you last week, @developit. What do you think of this? Anything you'd like added/removed/tidied up?

**Comment by wildlyinaccurate** [comment]
I've done my best to transfer the lifecycle docs for Zhongwen and Portuguese but it does leave the page a little empty compared to the English version.

**Comment by developit** [comment]
@wildlyinaccurate I changed two things (split into 2 commits) - let me know if that makes sense.  Otherwise I think we're good to go!

**Comment by wildlyinaccurate** [comment]
Thanks for clarifying those sections! Makes much more sense now. I'm happy if you are 🎉

**Comment by developit** [comment]
Yup!

**Pull request merged**
