### PR TITLE
[WIP] Translate website in french

### LINKED ISSUE #97: Translate to French
/cc @xtuc

#### Process:

- Copy everything except `lang` from `content/` into `content/lang/fr/`
- Translate the markdown files
- Add "fr" to the [list of languages](https://github.com/developit/preact-www/blob/master/src/config.json#L7)

### PR DESCRIPTION
**Pull request by xtuc**
Fixes #97

### CODE REVIEW

**Comment by drazik** [comment]
Hello. I would like to help you on this. How can I add some files to this PR ?

**Comment by xtuc** [comment]
Yes, sure go ahead, thanks.

**Comment by drazik** [comment]
@xtuc How can I do this ? I don't know how to add changes to someone else's PR

**Comment by xtuc** [comment]
I added you as collaborator on my fork. We can clone my repo and push on the branch (the PR will be updated).

**Comment by developit** [comment]
Think we can merge this? 😊

**Comment by xtuc** [comment]
We are still missing the homepage https://github.com/xtuc/preact-www/pull/1.

**Comment by xtuc** [comment]
@drazik did an amazing job! I think we're good? Are we still missing some pages?

**Comment by drazik** [comment]
Yeah @developit I think we are good on this one now. If somebody speaking french could do a last review it would be great. But @xtuc, @mlcdf and I translated and reviewed everything, so I think you can merge it as is.

**Pull request merged**
