### PR TITLE
Let user choose their own language instead of forcing the default

### PR DESCRIPTION
**Pull request by fdaciuk**
Even when you choose a different language, when you reload the page,
The language returns to the default of the browser. This change allows
you to choose the language you want.

cc @developit =)

### CODE REVIEW

**Comment by developit** [comment]
Gonna play with this locally before merging. Looks good though.

**Comment by fdaciuk** [comment]
Nice @developit =)

**Comment by fdaciuk** [comment]
@developit you forgot me :cry: :joy: :joy:

**Comment by developit** [comment]
I am literally the worst :(
Benedikt even subtweeted this issue and I still haven't had time 💀

**Comment by fdaciuk** [comment]
haha! No problem man =)
If you want any help, let me know :D

**Pull request merged**
