### PR TITLE
Mirgate to offline-plugin 4.5.2

### PR DESCRIPTION
**Pull request by NekR**
Something like this :-) I removed unnecessary options and added new ones introduced in `v4` of `offline-plugin`. For example, I removed `ServiceWorker.navigateFallbackURL` which was a temporary solution for app-shell in `offline-plugin` (it was kind of emulation AppCache's behavior with FALLBACK) and added `cacheMaps` which is official solution for app-shell in `offline-plugin` now.

@developit Please test it somehow. I did my testing and it seems fine, but I could easily miss something. You know this project better anyway :-)

### CODE REVIEW

**Comment by developit** [comment]
Trying to test this out locally. Might deploy to a staging env with HTTPS to be sure.

**Comment by NekR** [comment]
Yeah, would be good. I think I can try on `now.sh`. The we need to test is SW upgrade. It should work fine, but just-in-case testing won't hurt.

**Comment by developit** [comment]
I have preact-www.surge.sh that I use as an alternate, should work there.

**Comment by developit** [comment]
@NekR do you think this will solve #58?

**Comment by NekR** [comment]
@developit #58 can be fixed by using `copy-webpack-plugin` with any version of `offline-plugin`. What v4 brings (in case of `preact-www`) is support of `network-first` response strategy. 

Also it's just better (4.5.4 is the latest btw).

**Comment by developit** [comment]
Also the externals cover non-webpack assets as well right?

**Comment by NekR** [comment]
@developit yes, `externals` is added specifically for such use cases. If you specify URLs files there then they will be caches alongside with webpack generated assets.

`externals` accepts URLs btw, not FS paths. But something like `/images/foo.jpg` or `images/foo.jpg` also works (transformed to URL, not FS checks of course).

**Pull request merged**
