### PR TITLE
Update links and docs in ES and ZH

### PR DESCRIPTION
**Pull request by vitormalencar**
- Remove dead links in ES and ZH
- Update linked state to Preact 8 in ES

I would really like to update linked state docs in Chinese, but I do not have as much skill in the language 🙇.

### CODE REVIEW

**Comment by developit** [comment]
@vitormalencar think we're good to merge this? :)

**Comment by vitormalencar** [comment]
yep @developit  this should also  help close the #68  

if you want I can doble check the links 👍

**Comment by developit** [comment]
Might be worth a double check yup.

**Comment by vitormalencar** [comment]
- [x] doble check all the links
- [x] review the text

I think that we are good to go 😄

**Comment by vitormalencar** [comment]
hey man, 😄  any update?

**Pull request merged**
