### PR TITLE
Translated to Brazilian Portuguese 🇧🇷

### PR DESCRIPTION
**Pull request by joaolucasl**
Thanks for Preact - it's awesome! I decided to translate the website to PT-BR as a way to spread some love to OSS and give back to this incredible project!

Let me know if something needs fixing, I'll gladly update it! :D

### CODE REVIEW

**Comment by developit** [comment]
This is amazing! Looking good so far, I'm going to test it out locally.

**Comment by developit** [comment]
Merged and deployed!
Your documentation is lovely: https://preactjs.com/?lang=pt-br
screen shot 2016-12-04 at 1 32 33 pm

**Comment by developit** [comment]
Only thing I was curious about - is there a slightly shorter was to say "Um tipo diferente de biblioteca"?  Like is there a slang/shortform like "js lib" in Portuguese?  Let me know :)

**Comment by joaolucasl** [comment]
mmm, I think "Um novo tipo de biblioteca" (A new kind of library) fits better, if that's okay.  In Brazil we use "lib" informally, but is not as widespread as the Portuguese word "biblioteca".

image

**Comment by developit** [comment]
That works for me! Want to PR or shall I?

**Comment by joaolucasl** [comment]
Doing that rn!

**Pull request merged**
