### PR TITLE
Remove ears from code blocks

### PR DESCRIPTION
**Pull request by sapegin**
Before:

image 2017-01-18 at 7 06 00 pm

After:

image 2017-01-18 at 7 05 17 pm

### CODE REVIEW

**Comment by developit** [comment]
Need to try this out locally but it looks good!

**Comment by sapegin** [comment]
@developit Have you had time to try it? ;-)

**Comment by developit** [comment]
Not yet, will be a couple days before I can get around to anything.

**Comment by developit** [comment]
Sorry for the silly wait there 😇

**Pull request merged**
