### PR TITLE
Remove dead links in Big Performance section

### PR DESCRIPTION
**Pull request by vandrijevik**
The second paragraph in the **Big Performance** section on https://preactjs.com/ currently reads:

> It even includes extra performance features like customizable update batching, optional async rendering, DOM recycling and optimized event handling via Linked State.

The features “customizable update batching” and “optional async rendering” contain broken links that lead to 404 pages. This PR removes them, so the paragraph is simpler and contains a link to the valid guide for Linked State.

### CODE REVIEW

**Comment by developit** [comment]
@vandrijevik Thanks for submitting this - maybe we should keep the text, but not have it linked to anything?

**Comment by vandrijevik** [comment]
@developit That sounds fine to me! I wasn’t sure about the state of those claims, but if you think they are worth mentioning I will certainly put them back.

**Comment by developit** [comment]
Ah yeah - both definitely supported, just we haven't yet written documentation about them that could be linked there.  Still worth calling them out :)

**Comment by vandrijevik** [comment]
@developit Sounds good to me! I added 21764f8 so that diff should look better now 😄 Are two separate commits okay, or would you prefer that I squash them into one?

**Comment by developit** [comment]
Great, thanks!

**Pull request merged**
