### PR TITLE
Reworded 'a different kind of lib' in PT-BR to fit in a single line

### PR DESCRIPTION
**Pull request by joaolucasl**
As per the convo in #63, I reworded the headline to fit in a single line

### CODE REVIEW

**Comment by developit** [comment]
Perfect!

**Comment by joaolucasl** [comment]
Oh man, the "dot" in the end of the sentence makes it split into two lines! Trying to find a new phrase that fits.

**Comment by developit** [comment]
Whoops! I just merged! lol

**Comment by joaolucasl** [comment]
I'll try and find a new one and PR again when I have it. Sorry about it.

**Comment by developit** [comment]
lol no problem

**Pull request merged**
