### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by bmatzner**

### CODE REVIEW

**Comment by developit** [comment]
This is looking really awesome guys!  Think it's ready to merge? 💃

**Comment by ForsakenHarmony** [comment]
Seems like we already merged a German translation ignoring this :/

**Comment by developit** [comment]
I think it was derived from this work?

**Comment by ForsakenHarmony** [comment]
I don't think so?
"Wrote everything from scratch yesterday"
but we have german so we can close this ig

**Comment by developit** [comment]
makes me feel bad :(

**Comment by ForsakenHarmony** [comment]
yeah, it's meh
but as said in the other pr there has been nothing from him yet

**Comment by bmatzner** [comment]
I don't know why this was left untouched last year, disappointing, but s*!$ happens. Life goes on… ;-)

**Pull request closed without merging**
